def get_level(xp):
    return min(xp // 200 + 1, 10)

item_emojis = {
    "Rusty Dagger": "🗡️",
    "Torn Pouch": "🏹",
    "Small Gem": "💎",
    "Cracked Fang": "⚔️",
    "Wolf Fang": "🦴",
    "Tattered Hide": "🧥",
    "Cracked Stone": "🪨",
    "Magic Core": "🔮",
    "Heavy Rock": "🏗️",
    "Slime Essence": "🧪",
    "Sticky Gel": "🔵",
    "Poison Fang": "🕷️",
    "Spider Silk": "🕸️",
    "Webbed Arrow": "🏹",
    "Lizard Scale": "🦎",
    "Venom Blade": "🗡️",
    "Fire Gland": "🔥",
    "Deer Antler": "🏹",
    "Soft Fur": "🧥",
    "Mystic Leaf": "🍁",
    "Frog Leg": "🐸",
    "Lucky Charm": "🍀",
    "Toxic Slime": "🧪",
    "Explosive Powder": "💣",
    "Glowing Eye": "🟩",
    "Ashes": "🔥",
    "Basic Armour": "🛡️",
    "Sword": "⚔️",
    "Golden Apples": "🍏",
    "Life Potion": "🧪",
    "Dragon Scale": "🐉",
    "Titan's Heart": "❤️",
    "Hydra Venom": "🐍",
    "Ancient Relic": "🏺",
    "Shadow Orb": "⚫",
    "Demon Horn": "👹",
    "Phoenix Feather": "🪶",
    "Eldritch Tome": "📜",
    "Warrior's Medal": "🎖️",
    "Hunt": "⚔️",
    "Adventure": "🌄",
    "View Inventory": "🎒",
    "View Profile": "🧑",
    "Store": "🏪",
    "Heal using Life Potion": "💖",
    "Delete User": "❌",
    "Exit": "🚪",
    "Chop_woods": "🪓",
    "Reward": "🏆",
    "Sharp Tooth": "🦷",
    "Bear Claw": "🐻",
    "Fur Pelt": "🦊",
    "Slime Gel": "🧪",
    "Sticky Residue": "🟡",
    "Glowing Core": "🔆",
    "Spider Leg": "🕷️",
    "Silk Thread": "🧵",
    "Venom Sac": "🕸️",
    "Reptile Scale": "🦎",
    "Sharp Claw": "🦅",
    "Venom Gland": "🧪",
    "Hoof": "🐴",
    "Slippery Skin": "🦎",
    "Croak Sac": "🐸",
    "Creeper Dust": "🌫️",
    "Explosive Core": "💥",
    "Fragmented Shell": "🐚",
}
